import { palette } from "./domain";

export const ui = {
  color: {
    ...palette,
    surface: palette.white,
    surfaceWarm: palette.paper,
    surfaceSoft: palette.chalk,
    textPrimary: palette.ink,
    textSecondary: palette.muted,
    outline: palette.line,
    actionPrimary: palette.blue,
    actionConfirm: palette.green,
    actionWarn: palette.yellow,
    actionHot: palette.court,
    sliderTrack: 0xe6ddc9,
    disabledText: 0xa29580,
    dividerSoft: 0xe3d4b4,
    dividerLight: 0xfffbec,
    memoryPaper: 0xfff0d2,
    inputFill: 0xfffbf0,
    cameraDark: 0x1f2526,
    ageBadgeBg: 0xe9f7df,
    ageBadgeGreen: 0x63c63d,
    coinFill: 0xfff3ba,
  },
  font: {
    family: "PingFang SC, Microsoft YaHei, sans-serif",
    size: {
      micro: 10,
      legal: 11,
      caption: 12,
      chip: 13,
      helper: 14,
      body: 16,
      list: 18,
      subhead: 20,
      section: 22,
      navTitle: 23,
      panelTitle: 24,
      display: 30,
      hero: 32,
    },
    weight: {
      regular: "500",
      medium: "700",
      semibold: "800",
      bold: "900",
    } as const,
    lineHeight: {
      tight: 17,
      body: 24,
      relaxed: 28,
    },
    containerTextOffsetY: 1,
  },
  textStyle: {
    headerTitle: { size: 23, weight: "800" },
    pageTitle: { size: 28, weight: "900" },
    panelTitle: { size: 24, weight: "900" },
    sectionTitle: { size: 20, weight: "800" },
    itemTitle: { size: 16, weight: "900" },
    itemDesc: { size: 13, weight: "500", lineHeight: 17 },
    body: { size: 16, weight: "700", lineHeight: 24 },
    hudText: { size: 17, weight: "800" },
    legalText: { size: 11, weight: "800" },
    buttonText: { size: 17, weight: "700" },
  },
  radius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    pill: 999,
    phone: 18,
  },
  stroke: {
    thin: 1,
    default: 2,
    heavy: 4,
  },
  space: {
    xxs: 4,
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    section: 30,
    panel: 36,
  },
  layout: {
    header: {
      x: 18,
      y: 16,
      height: 58,
      titleX: 38,
      titleY: 27,
      buttonY: 26,
      buttonH: 38,
    },
    settings: {
      navX: 56,
      panelX: 304,
      contentY: 104,
      navW: 218,
      panelW: 600,
      panelH: 350,
      rowH: 46,
      rowGap: 8,
      rowStep: 54,
    },
  },
  component: {
    button: {
      radius: 8,
      primaryFill: palette.blue,
      secondaryFill: palette.muted,
      dangerFill: palette.red,
      hotFill: palette.court,
      ghostFill: palette.paper,
    },
    settingsControl: {
      width: 92,
      height: 30,
      switchKnob: 10,
      sliderWidth: 136,
      sliderH: 8,
      sliderKnob: 12,
      segmentWidth: 46,
    },
  },
} as const;

export type FontWeightToken = (typeof ui.font.weight)[keyof typeof ui.font.weight];
